development:
    source: ${dropbox}/Elfenrausch-Gallerie
    work: ${dropbox}/Customers/Elfenrausch/Galerie
    
production:
    source: ${dropbox}/Elfenrausch-Gallerie
    work: ${dropbox}/Customers/Elfenrausch/Galerie
    destination: rsync+ssh://elfenrausch.de:web/elfenrausch.de/galerie/
